# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import Qt
import pandas as pd
import pymongo
from PyQt5 import QtWidgets

myclient = pymongo.MongoClient("mongodb://localhost:27017/")
db = myclient["Employee"]
#collection 
collection_Employee=db.Employee

class Ui_Form(object):

    def exportToExcel(self):
        df = pd.DataFrame(list(collection_Employee.find()))
        df.to_excel("C:\\Users\\LENOVO\\Desktop\\atelier\\biblio1\\DataBase.xlsx", index=False)
        msg = QMessageBox()
        msg.setWindowTitle("EXPORT")
        msg.setIcon(QMessageBox.Information)
        msg.setText("Data Export Successfully")
        retval = msg.exec_() 
        

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(130, 120, 151, 51))
        self.pushButton.setStyleSheet("font: 11pt \"Rockwell\";\n"
"background-color: rgb(170, 85, 255);")
        self.pushButton.setObjectName("pushButton")

        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

        self.pushButton.setText(_translate("Form", "E X P O R T"))
        self.pushButton.clicked.connect(self.exportToExcel)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
