# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication
from PyQt5.QtWidgets import QMessageBox
import pymongo
import Admin
import facture



#Database
client = pymongo.MongoClient()
#create database
mydb=client["RetailManagmentSystem"]
#create a collection 
Users=mydb["Users"]




class Ui_Login(object):
    def GoTo(self):
        if (self.UserRole.currentText() == "Employee"):
            # get text
            username=self.UsernameInput.text()
            password=self.PasswordInput.text()
            # Check
            print("\n logged in with ", username,"and ", password)
            #  search
            result = mydb.Users.find_one({"username": username, "password": password, "type": "employee"})
            if (result == None):
                print("\n Not Found!")
                msg = QMessageBox()
                msg.setWindowTitle("ERROR")
                msg.setIcon(QMessageBox.Critical)
                msg.setText("invalid username or password")
                retval = msg.exec_()
            else:
                print("\n houni n7otou interface bill hhh")
                self.EmployeeDashboard = QtWidgets.QWidget()
                self.ui = facture.Ui_EmployeeDashboard()
                self.ui.setupUi(self.EmployeeDashboard)
                self.EmployeeDashboard.show()


        elif (self.UserRole.currentText() == "Admin"):
            # get text
            username=self.UsernameInput.text()
            password=self.PasswordInput.text()
            # Check
            print("\n logged in with ", username,"and ", password)
            #Recherche
            result = mydb.Users.find_one({"username": username, "password": password, "type": "admin"})
            if (result == None):
                print("\n Not Found!")
                msg = QMessageBox()
                msg.setWindowTitle("ERROR")
                msg.setIcon(QMessageBox.Critical)
                msg.setText("invalid username or password")
                retval = msg.exec_()
            else:
                # go to Admin interface
                self.Admin = QtWidgets.QMainWindow()
                self.ui = Admin.Ui_pageAdmin()
                self.ui.setupUi(self.Admin)
                self.Admin.show()
                


    
        
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1284, 729)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(1280, 720))
        Login.setBaseSize(QtCore.QSize(1280, 720))
        Login.setStyleSheet("#Login{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(182, 74, 108, 255), stop:1 rgba(64, 48, 148, 255));\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("#Title{\n"
"    \n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.UserRole = QtWidgets.QComboBox(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.UserRole.sizePolicy().hasHeightForWidth())
        self.UserRole.setSizePolicy(sizePolicy)
        self.UserRole.setMinimumSize(QtCore.QSize(200, 35))
        self.UserRole.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserRole.setFont(font)
        self.UserRole.setStyleSheet("")
        self.UserRole.setEditable(False)
        self.UserRole.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.UserRole.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.UserRole.setFrame(True)
        self.UserRole.setObjectName("UserRole")
        self.UserRole.addItem("")
        self.UserRole.addItem("")
        self.verticalLayout.addWidget(self.UserRole, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.FormContainer = QtWidgets.QWidget(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.FormContainer.sizePolicy().hasHeightForWidth())
        self.FormContainer.setSizePolicy(sizePolicy)
        self.FormContainer.setStyleSheet("#FormContainer{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.FormContainer.setObjectName("FormContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FormContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.FormContainer)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Avatar = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(140)
        sizePolicy.setVerticalStretch(140)
        sizePolicy.setHeightForWidth(self.Avatar.sizePolicy().hasHeightForWidth())
        self.Avatar.setSizePolicy(sizePolicy)
        self.Avatar.setMinimumSize(QtCore.QSize(140, 140))
        self.Avatar.setMaximumSize(QtCore.QSize(140, 140))
        self.Avatar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Avatar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Avatar.setText("")
        self.Avatar.setPixmap(QtGui.QPixmap("../assets/avatar.png"))
        self.Avatar.setScaledContents(True)
        self.Avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.Avatar.setObjectName("Avatar")
        self.horizontalLayout_2.addWidget(self.Avatar)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.Form = QtWidgets.QWidget(self.FormContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form.sizePolicy().hasHeightForWidth())
        self.Form.setSizePolicy(sizePolicy)
        self.Form.setObjectName("Form")
        self.formLayout = QtWidgets.QFormLayout(self.Form)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.UsernameLabel = QtWidgets.QLabel(self.Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setScaledContents(True)
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.UsernameLabel)
        self.UsernameInput = QtWidgets.QLineEdit(self.Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsernameInput.sizePolicy().hasHeightForWidth())
        self.UsernameInput.setSizePolicy(sizePolicy)
        self.UsernameInput.setMinimumSize(QtCore.QSize(300, 30))
        self.UsernameInput.setMaximumSize(QtCore.QSize(300, 30))
        self.UsernameInput.setObjectName("UsernameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.UsernameInput)
        self.PasswordLabel = QtWidgets.QLabel(self.Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.PasswordLabel)
        self.PasswordInput = QtWidgets.QLineEdit(self.Form)
        self.PasswordInput.setMinimumSize(QtCore.QSize(300, 30))
        self.PasswordInput.setMaximumSize(QtCore.QSize(300, 30))
        self.PasswordInput.setObjectName("PasswordInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PasswordInput)
        self.verticalLayout_2.addWidget(self.Form, 0, QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(self.FormContainer)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.Submit = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Submit.sizePolicy().hasHeightForWidth())
        self.Submit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Submit.setFont(font)
        self.Submit.setStyleSheet("#Submit{\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.Submit.setObjectName("Submit")
        self.Submit.clicked.connect(self.GoTo)
        self.horizontalLayout.addWidget(self.Submit)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.FormContainer, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.Title.setText(_translate("Login", "Retail Management System"))
        self.UserRole.setItemText(0, _translate("Login", "Admin"))
        self.UserRole.setItemText(1, _translate("Login", "Employee"))
        self.UsernameLabel.setText(_translate("Login", "Username"))
        self.PasswordLabel.setText(_translate("Login", "Password"))
        self.Submit.setText(_translate("Login", "Login"))
        self.Submit.clicked.connect(Login.close)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
