# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_us.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about_us(object):
    def setupUi(self, about_us):
        about_us.setObjectName("about_us")
        about_us.setWindowModality(QtCore.Qt.ApplicationModal)
        about_us.resize(591, 442)
        about_us.setStyleSheet("background-color: rgb(100, 17, 194);\n"
"background-color: rgb(127, 34, 232);\n"
"alternate-background-color: rgb(121, 0, 182);")
        self.textBrowser = QtWidgets.QTextBrowser(about_us)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 611, 91))
        self.textBrowser.setStyleSheet("background-color: rgb(203, 203, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(about_us)
        self.label.setGeometry(QtCore.QRect(90, 10, 381, 41))
        self.label.setStyleSheet("background-color: rgb(203, 203, 0);")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(about_us)
        self.textEdit.setGeometry(QtCore.QRect(230, 136, 301, 241))
        self.textEdit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(about_us)
        self.label_2.setGeometry(QtCore.QRect(260, 160, 261, 20))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(about_us)
        self.label_3.setGeometry(QtCore.QRect(240, 220, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(about_us)
        self.label_4.setGeometry(QtCore.QRect(240, 260, 81, 21))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(about_us)
        self.label_5.setGeometry(QtCore.QRect(240, 300, 71, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(about_us)
        self.label_6.setGeometry(QtCore.QRect(240, 340, 91, 21))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(about_us)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 121, 121))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../image.qrc/360_F_446441329_ZZ4AtuYHjDNXals44YCJrQldclwamZvJ.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(120, 120))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(about_us)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 340, 31, 21))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../image.qrc/800px-YouTube_full-color_icon_(2017).svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(about_us)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 330, 31, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../image.qrc/2048px-Instagram_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(about_us)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 330, 31, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../image.qrc/124010.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(about_us)
        self.label_7.setGeometry(QtCore.QRect(390, 220, 55, 16))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(about_us)
        self.label_8.setGeometry(QtCore.QRect(390, 260, 55, 16))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(about_us)
        self.label_9.setGeometry(QtCore.QRect(390, 300, 141, 16))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(about_us)
        QtCore.QMetaObject.connectSlotsByName(about_us)

    def retranslateUi(self, about_us):
        _translate = QtCore.QCoreApplication.translate
        about_us.setWindowTitle(_translate("about_us", "about us"))
        self.label.setText(_translate("about_us", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Retail Manegement System</span></p></body></html>"))
        self.label_2.setText(_translate("about_us", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Developper Information</span></p></body></html>"))
        self.label_3.setText(_translate("about_us", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.label_4.setText(_translate("about_us", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Contact:</span></p></body></html>"))
        self.label_5.setText(_translate("about_us", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Email:</span></p></body></html>"))
        self.label_6.setText(_translate("about_us", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Follow Us:</span></p></body></html>"))
        self.label_7.setText(_translate("about_us", "AMNA"))
        self.label_8.setText(_translate("about_us", "55697897"))
        self.label_9.setText(_translate("about_us", "amna.hdhili@gmail.com"))

import source
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about_us = QtWidgets.QWidget()
    ui = Ui_about_us()
    ui.setupUi(about_us)
    about_us.show()
    sys.exit(app.exec_())
