# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_password(object):
    def setupUi(self, password):
        password.setObjectName("password")
        password.setWindowModality(QtCore.Qt.WindowModal)
        password.resize(418, 347)
        self.pushButton = QtWidgets.QPushButton(password)
        self.pushButton.setGeometry(QtCore.QRect(170, 240, 121, 28))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(password)
        self.label.setGeometry(QtCore.QRect(50, 50, 71, 20))
        self.label.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(password)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 91, 20))
        self.label_2.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(password)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 91, 16))
        self.label_3.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(password)
        self.lineEdit.setGeometry(QtCore.QRect(160, 50, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(password)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 110, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(password)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 180, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(password)
        self.label_4.setGeometry(QtCore.QRect(-10, 40, 71, 41))
        self.label_4.setStyleSheet("image: url(:/newPrefix/360_F_446441329_ZZ4AtuYHjDNXals44YCJrQldclwamZvJ.jpg);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(password)
        self.label_5.setGeometry(QtCore.QRect(-20, 100, 71, 31))
        self.label_5.setStyleSheet("image: url(:/newPrefix/lock+password+protect+safety+security+icon-1320086045132546966.png);\n"
"image: url(:/newPrefix/lock+password+protect+safety+security+icon-1320086045132546966.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(password)
        self.label_6.setGeometry(QtCore.QRect(-20, 170, 71, 31))
        self.label_6.setStyleSheet("image: url(:/newPrefix/lock+password+protect+safety+security+icon-1320086045132546966.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(password)
        QtCore.QMetaObject.connectSlotsByName(password)

    def retranslateUi(self, password):
        _translate = QtCore.QCoreApplication.translate
        password.setWindowTitle(_translate("password", "change password"))
        self.pushButton.setText(_translate("password", "change password"))
        self.label.setText(_translate("password", "user name"))
        self.label_2.setText(_translate("password", "old password"))
        self.label_3.setText(_translate("password", "new password"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    password = QtWidgets.QWidget()
    ui = Ui_password()
    ui.setupUi(password)
    password.show()
    sys.exit(app.exec_())
