# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emplyee.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_employee(object):
    def setupUi(self, employee):
        employee.setObjectName("employee")
        employee.setWindowModality(QtCore.Qt.WindowModal)
        employee.resize(387, 366)
        self.label = QtWidgets.QLabel(employee)
        self.label.setGeometry(QtCore.QRect(100, 0, 181, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(employee)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(employee)
        self.label_3.setGeometry(QtCore.QRect(270, 80, 81, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(employee)
        self.pushButton.setGeometry(QtCore.QRect(30, 130, 101, 81))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../image.qrc/20698.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(employee)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 130, 93, 81))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../image.qrc/360_F_446441329_ZZ4AtuYHjDNXals44YCJrQldclwamZvJ.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(120, 120))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(employee)
        self.label_4.setGeometry(QtCore.QRect(50, 230, 55, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(employee)
        self.label_5.setGeometry(QtCore.QRect(260, 230, 55, 31))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(employee)
        QtCore.QMetaObject.connectSlotsByName(employee)

    def retranslateUi(self, employee):
        _translate = QtCore.QCoreApplication.translate
        employee.setWindowTitle(_translate("employee", "employee"))
        self.label.setText(_translate("employee", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Total Users</span></p></body></html>"))
        self.label_2.setText(_translate("employee", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Employee</span></p></body></html>"))
        self.label_3.setText(_translate("employee", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Admin</span></p></body></html>"))
        self.label_4.setText(_translate("employee", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">(3)</span></p></body></html>"))
        self.label_5.setText(_translate("employee", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">(1)</span></p></body></html>"))

import source
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    employee = QtWidgets.QWidget()
    ui = Ui_employee()
    ui.setupUi(employee)
    employee.show()
    sys.exit(app.exec_())
