# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_product(object):
    def setupUi(self, product):
        product.setObjectName("product")
        product.setWindowModality(QtCore.Qt.WindowModal)
        product.resize(436, 394)
        product.setStyleSheet("background-color: rgb(255, 255, 255);")
        product.setModal(True)
        self.label = QtWidgets.QLabel(product)
        self.label.setGeometry(QtCore.QRect(90, 20, 211, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(product)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 51, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(product)
        self.label_3.setGeometry(QtCore.QRect(140, 70, 221, 201))
        self.label_3.setStyleSheet("image: url(:/newPrefix/products.png);\n"
"image: url(:/newPrefix/products.png);\n"
"image: url(:/newPrefix/products.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(product)
        QtCore.QMetaObject.connectSlotsByName(product)

    def retranslateUi(self, product):
        _translate = QtCore.QCoreApplication.translate
        product.setWindowTitle(_translate("product", "products"))
        self.label.setText(_translate("product", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">total products</span></p></body></html>"))
        self.label_2.setText(_translate("product", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">(9)</span></p></body></html>"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    product = QtWidgets.QDialog()
    ui = Ui_product()
    ui.setupUi(product)
    product.show()
    sys.exit(app.exec_())
